<?php
define('DB_NAME', 'local');
define('DB_USER', 'root');
define('DB_PASSWORD', 'root');
define('DB_HOST', 'localhost');
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');
define('WP_POST_REVISIONS', 3);
define('DISALLOW_FILE_EDIT', true);
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);
@ini_set('display_errors', 0);
define('FORCE_SSL_ADMIN', true);
define('DISALLOW_FILE_MODS', true);
define('ABSPATH', __DIR__ . '/');
define('AUTH_KEY', ':1%%1G)E?M0Q/@Z8s_Ls6gLMh`BuPOFe_h>PkWP[Kh~Dgh$Q|DM+($B sfd0-g8T');
define('SECURE_AUTH_KEY', 'R{#DRdRj@BtM kRr46+Vy$=~O0;6II;)v872<CH=HX6^EG+V:bepo]oq/_J}|>G0');
define('LOGGED_IN_KEY', '9N7S2Eh-l|@>id7:Q%b-9:ZcK@B?dLF@qnZno< !coa|Y3s,>+imcCXPluPg~f x');
define('NONCE_KEY', '-QxE-QYSR{Y~|u2o+kkQ._L1 Eb|(h180#8B=8/7&J=o$+aEw=wkGYrSe3Pq[-+G');
define('AUTH_SALT', 'Y7l8gVF,LXr]z:=TLeubbN0<(xCJNJvZs0C/fbe4es,:!IYip4+p3h&|tTiS5|} ');
define('SECURE_AUTH_SALT', 'Z9cybW&CVR9|{W@)byZynJU||-5NN,i*+BEYBLdrEVo[/ADlb3Ha_XwQuqbIz+dd');
define('LOGGED_IN_SALT', ',@:9Y[c?/o<-s$%:28,6cG[^x$3-C*}Dw%X-idk_-qwze9Ne 2kTY}z1&+4MjZN2');
define('NONCE_SALT', '(e|zyKE1/cxvPZTh5 y~yDs1bKO+ks<%!(+#@BQLld+34!PhW.9AwOo?~UbZ4tk9');
$table_prefix = 'wp_';
require_once ABSPATH . 'wp-settings.php';
